server:
  port: 8888

spring:
  profiles:
    active: default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/anbuvin/springboot-ref-config
          username: ${GIT_USERID}
          password: ${GIT_PASSWORD}

---

spring:
  profiles: docker

eureka:
  instance:
    hostname: discovery
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0

---

spring:
  profiles: default

eureka:
  client:
    registerWithEureka: true
  server:
    waitTimeInMsWhenSyncEmpty: 0
