spring:
  cloud:
    stream:
      bindings:
        output:
          destination: venuetopic
          content-type: application/json
          group: venuegroup
          resetOffsets: true
      kafka:
        binder:
          brokers: localhost:9092